### ISSUE TITLE
Question about toJson/toYaml

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/sdk-typescript#100]
**What is the question**:

Running this code:

```text
import { WorkflowConverter, workflowBuilder, injectstateBuilder, Specification } from '@severlessworkflow/sdk-typescript';

const workflow: Specification.Workflow = workflowBuilder()
  .id("helloworld")
  .version("1.0")
  .name("Hello World Workflow")
  .description("Inject Hello World")
  .start("Hello State")
  .states([
    injectstateBuilder()
      .name("Hello State")
      .data({
          "result": "Hello World!"
      })
      .end(true)
      .build()
  ])
  .build();

  const workflowAsYaml: string = WorkflowConverter.toYaml(workflow);

  console.log(workflowAsYaml);
```

the output is really cool and correct - no issues there

```yaml
id: helloworld
version: '1.0'
name: Hello World Workflow
description: Inject Hello World
start: Hello State
states:
  - name: Hello State
    data:
      result: Hello World!
    end: true
    type: inject
```

I am just wondering if it's possible to spit out the state type right after the name and not have it last? like:

```yaml
id: helloworld
version: '1.0'
name: Hello World Workflow
description: Inject Hello World
start: Hello State
states:
  - name: Hello State
    type: inject
    data:
      result: Hello World!
    end: true
```

Any pointers where this order can be changed please let me know I'd love to help fix this :)
